raw_data:
  raw_gene_data_path: "./data/Wu_etal_2021_BRCA_scRNASeq/count_matrix_genes.tsv"
  raw_metadata_path: "./data/Wu_etal_2021_BRCA_scRNASeq/metadata.csv"
  raw_barcodes_path: "./data/Wu_etal_2021_BRCA_scRNASeq/count_matrix_barcodes.tsv"
  raw_mtx_path: "./data/Wu_etal_2021_BRCA_scRNASeq/count_matrix_sparse.mtx"

updated_data:
  updated_data_path: "./data/"

qc: #quality control/preprocessing
  n_feature_min: 200
  n_feature_max: 5000 #2500
  n_count_min: 500
  n_count_max: 20000 #25000
  percent_mt_max: 15 #10

features: #feature selection
  n_highvarfeats: 2000 #number of features chosen for analysis
  n_feats: 20 #top n features to be displayed
  n_labels: 10

pca:
  n_vars: 20 #number of genes/features per PC
  pc_range: [1,2] #range of PCs to be displayed

plots:
  display_qc_metrics: False