#cluster cell labels
0: VWF - ADIPOCYTES OR ENDOTHELIAL CELLS
1: GPR171 - T CELLS
2: GZMB - DENDRITIC OR NK CELLS
3: MS4A1 - B cells
4: CRYAB -  CARDIOMYOCYTES OR PROXIMAL TUBULAR CELLS OR SKELETAL MYOCYTES
5: CTSK - fibroblasts
6: SCGB2B2/DKK1 - OLIGODENDROCYTES OR ENDOMETRIAL STROMAL CELLS
7: IGKV1-5 - PLASMA CELLS
8: NDUFA4L2 - SMOOTH MUSCLE CELLS OR KERATINOCYTES 
9: KRT14 - BASAL KERATINOCYTES
10: CD24 - EPITHELIAL CELLS
11: S100A8 - SUPRABASAL KERATINOCYTES
12: ANKRD30A - BREAST GLANDULAR CELLS
13: AGR3 - PROXIMAL ENTEROCYTES
14: HMOX1 - KUPFFER CELLS OR TROPHOBLASTS
15: IGHG1 - PLASMA CELLS
16: FTL - HOFBAUER CELLS